"""Initial schema

Revision ID: 3265caf90a58
Revises: 
Create Date: 2026-06-03 16:39:27.687457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3265caf90a58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergen_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon_emoji', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ocr_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('ocr_text', sa.String(), nullable=True),
    sa.Column('ingredients_extracted', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('warnings_extracted', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(), server_default='', nullable=False),
    sa.Column('city', sa.String(), server_default='Manta', nullable=False),
    sa.Column('language', sa.String(), server_default='es-EC', nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allergens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scientific_names', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('synonyms', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('ocr_variants', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['allergen_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('ingredients_raw', sa.String(), nullable=True),
    sa.Column('ingredients_array', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('verified_by_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('country_origin', sa.String(), server_default='EC', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verified_by'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_table('product_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reported_by', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('result_status', sa.String(), nullable=False),
    sa.Column('scan_source', sa.String(), server_default='camera', nullable=False),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.Column('detected_allergens', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('ingredients_found', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('from_cache', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_allergies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('allergen_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(), server_default='high', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_allergies')
    op.drop_table('scan_history')
    op.drop_table('product_reports')
    op.drop_table('products')
    op.drop_table('allergens')
    op.drop_table('profiles')
    op.drop_table('ocr_cache')
    op.drop_table('allergen_categories')
    # ### end Alembic commands ###
